package com.mindex.challenge.service.impl;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.mindex.challenge.dao.CompensationRepository;
import com.mindex.challenge.dao.EmployeeRepository;
import com.mindex.challenge.data.Compensation;
import com.mindex.challenge.data.Employee;
import com.mindex.challenge.service.CompensationService;
import com.mindex.challenge.service.EmployeeService;

@Service
public class CompensationServiceImpl implements CompensationService {

	 @Autowired
	    private EmployeeService employeeService;
	
	 @Autowired
	    private CompensationRepository compensationRepository;
	 
	 
	@Override
	public Compensation create(Compensation compensation) {
		// gets employee object from compensation object
		Employee emp = compensation.getEmployee();
		// inserts into employee repo
		Employee emp2 = employeeService.create(emp);
		// get the newly created employee id (during employee insert gets autogenerated)
		// and assign it to our compensation object so we can look it up later.
		compensation.getEmployee().setEmployeeId(emp2.getEmployeeId());
		
		// maybe reformat the date
		Date effDate = compensation.getEffectiveDate();		
		
		compensationRepository.insert(compensation);			
		
		return compensation;
	}

	@Override
	public Compensation read(String id) {
		// find compensation object based on employee id		
		Employee e = employeeService.read(id);	
		Compensation comp = compensationRepository.findByEmployee(e);
		if(id.equals(comp.getEmployee().getEmployeeId()))
		{
			return comp;
		}
		
		return null;
	}
	@Override
	public List<Compensation> read() {
		List<Compensation> compensationList = compensationRepository.findAll();
		return compensationList;
		
	}
}
